# ?????? ??? ???????? Gradle ? ????????? ??????.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# ?????????? AndroidX.
android.useAndroidX=true

# ??????????? Kotlin code style.
kotlin.code.style=official

# ?????? ?????? ???????? ??????????? R-????? (??????? ??????).
android.nonTransitiveRClass=true

# ???????? ??????????? ??????.
org.gradle.caching=true